spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cangqiong
  mvc:
      pathmatch:
        matching-strategy: ant_path_matcher
  main:
    allow-circular-references: true
  redis:
    open: true
    port: 6379
    host: localhost
    database: 1
mybatis:
  configuration:
    map-underscore-to-camel-case: true
sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: guoguo
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: guoguo
    user-ttl: 7200000
    # 设置前端传递过来的令牌名称
    user-token-name: authentication
  alioss:
    bucket-name: 
    endpoint: 
    access-key-secret: 
    access-key-id: 
  wechat:
    appid:   #微信小程序申请的账号
    secret:  #微信小程序开发的密钥
    mchid:    #商户号
    mchSerialNo:   #商户证书序列号
    privateKeyFilePath: D:\pay\apiclient_key.pem  #商户私钥  存在本地文件了
    apiV3Key: CZBK51236435wxpay435434323FFDuv3   #apiV3密钥
    weChatPayCertFilePath: D:\pay\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem   #微信支付证书  存在本地文件了
    notifyUrl: https://58869fb.r2.cpolar.top/notify/paySuccess  #支付成功回调   https://58869fb.r2.cpolar.top 临时域名  notify/paySuccess是controller请求路径
    refundNotifyUrl: https://58869fb.r2.cpolar.top/notify/refundSuccess  #退款成功回调  https://58869fb.r2.cpolar.top 临时域名
